name: Android Debug Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace --build-cache -Dorg.gradle.jvmargs="-Xmx4g"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: rpcsx-debug
          path: app/build/outputs/apk/debug/*.apk
